parameters:
    account_logger:
        timezone:     "America/New_York"

services:

    account_logger_service:
        class:      SAS\IRAD\GmailAccountLogBundle\Service\AccountLoggerService
        arguments:  [ @doctrine.orm.entity_manager, %account_logger% ]